### ISSUE TITLE
trouble opening project in CLion on Linux

### ISSUE THREAD

**Issue by ipsod** [platisd/reusable-testable-arduino-tutorial#6]
Hi.  I use CLion for other stuff, but am having trouble with intellisense inside of this project.  I just resumed watching the video and see that you have the same thing happening on your version.  I'll continue watching and hope there's a fix - is there?

![trouble_with_arduino_ide](https://user-images.githubusercontent.com/2526835/150694931-3be001e6-59aa-4c7c-b3ec-59e9f8af0f54.png)

**Comment by platisd** [comment]
Not sure what problem you are referring to. Please elaborate further. :+1:

**Comment by ipsod** [comment]
I think I figured it out.

See all of the unrecognized variables in the file?  (everything red and the red-underlined stuff)
And, up top, below the "MagicCartController.ino" file, the message:
"This file does not belong to any project target..."

I think fixed it by right-clicking the MagicCartController folder (on Project tab), then click "Mark Directory As -> Project Sources and Headers".

**Comment by ipsod** [comment]
Do you see all of the unrecognized variables in the file, in the screenshot I posted above? That would be everything red (WebServer, ArduinoRuntime, ...) and the red-underlined stuff (every include).

I am wondering how I can get CLion to find those, so that I can use code-completion for them. I understand that I don't need to modify the code for the tutorial, but I was hoping to get it working for when I start developing my own project with tests.

**Comment by ipsod** [comment]
Also, thanks for the quick reply.  I didn't mean to be demeaning or terse, was just in a hurry.  Really enjoyed your tutorial, just trying to make the stuff I learned in it work for me.

**Comment by platisd** [comment]
No worries, I didn't notice the "IntelliSense" part in your question and I thought there was something wrong with the code.
The problem with those header files is that they are technically not part of the CMake project.
Furthermore, the Arduino sketch you have open is not built by CLion and this is why those header files are not picked up by IntelliSense and why it appears like its malfunctioning.

If you want to use CLion to properly develop for Arduino and not just the tests I suggest you install some plugin such as PlatformIO or whatever the suggested way is these days. Alternatively, you could find out where those headers are (probably somewhere in your `.arduino15` directory) and add them to the IDE's include path. I vaguely recall there's some setting somewhere for this. In any case I am afraid that setting up CLion for Arduino development is not _really_ part of this tutorial and I haven't done it myself to be honest. I typically use VS Code or the Arduino IDE directly.

**Comment by ipsod** [comment]
Oh, I see, thank you!
